export const UPDATE_CONFIG = 'UPDATE_CONFIG';
export const PRICE_FEED = 'PRICE_FEED';
export const AUTH_STATUS = 'AUTH_STATUS';

export const USER_LOGIN_IN_PROGRESS = 'USER_LOGIN_IN_PROGRESS';
export const USER_LOGIN_STATE_UPDATE = 'USER_LOGIN_STATE_UPDATE';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGNUP_IN_PROGRESS = 'USER_SIGNUP_IN_PROGRESS';
export const USER_SIGNUP_CONFIRM_REQUIRED = 'USER_SIGNUP_CONFIRM_REQUIRED';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const USER_SIGNUP_CONFIRM_IN_PROGRESS = 'USER_SIGNUP_CONFIRM_IN_PROGRESS';
export const USER_SIGNUP_CONFIRM_SUCCEES = 'USER_SIGNUP_CONFIRM_SUCCEES';
export const USER_SIGNUP_CONFIRM_ERROR = 'USER_SIGNUP_CONFIRM_ERROR';




